# Generated by Django 5.0.7 on 2024-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_image_alter_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answer_correct',
            field=models.IntegerField(default=0),
        ),
    ]
