# Generated by Django 5.0.7 on 2024-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_student_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='answer_correct',
            field=models.IntegerField(default=0),
        ),
    ]
