# Generated by Django 5.0.7 on 2024-08-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.CharField(default='No remark', max_length=100),
        ),
    ]
