# Generated by Django 5.0.7 on 2024-08-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_percentage_student_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='No grade', max_length=100),
        ),
    ]
